const TOURNAMENT_TURN_DURATION_MS = 30_000;
const TOURNAMENT_RECONNECT_GRACE_MS = 30_000;
const TOURNAMENT_READY_GRACE_MS = 180_000;

module.exports = { TOURNAMENT_TURN_DURATION_MS, TOURNAMENT_RECONNECT_GRACE_MS, TOURNAMENT_READY_GRACE_MS };
